name: PR Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t service:test .

      - name: Verify redis extension
        run: docker run --rm service:test php -m | grep -q redis

      - name: Verify runtime
        run: docker run --rm service:test php -v
