name: PR Check

on:
  pull_request:

jobs:
  checks:
    if: github.base_ref == 'development' || (github.base_ref == 'main' && github.head_ref == 'development')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Build Docker image
        if: github.base_ref == 'main'
        run: docker build -t service:test .

      - name: Verify runtime
        if: github.base_ref == 'main'
        run: docker run --rm service:test php -v
